"""Shared-account portfolio backtester for Experiment #001.

The portfolio engine evaluates all symbols together using one shared account.

Design rules:
- Long-only.
- One simultaneous position.
- Maximum three entries per day.
- Maximum 0.5% planned risk per trade.
- Maximum ₹10,000 position value.
- Maximum 1% daily loss.
- Signals are evaluated using information available at the current bar only.
- Entries execute at the next bar open.
- No overnight positions.
- Stop/target ambiguity is resolved conservatively in favor of the stop.
- Transaction costs and slippage are included.
- MAE/MFE are persisted for every completed trade.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable

import pandas as pd

from .config import Settings, load_settings
from .costs import CostSettings, calculate_trade_costs
from .risk import calculate_position_size
from .strategy import Signal, generate_signal


STRATEGY_NAME = "Trend + VWAP Pullback + Confirmation v2"
EXPERIMENT_NAME = "EXPERIMENT #001 — STRATEGY #002"

DEFAULT_DATA_ROOT = Path("data") / "processed"
DEFAULT_REPORT_ROOT = Path("data") / "reports"

SESSION_START = "09:15"
SESSION_END = "15:30"


@dataclass(frozen=True)
class PortfolioTrade:
    """Completed trade generated by the shared-account backtester."""

    symbol: str
    signal_time: pd.Timestamp
    entry_time: pd.Timestamp

    entry: float
    stop: float
    target: float
    quantity: int

    exit_time: pd.Timestamp
    exit: float

    gross_pnl: float
    total_cost: float
    net_pnl: float

    brokerage: float
    stt: float
    exchange_transaction_charges: float
    sebi_charges: float
    stamp_duty: float
    gst: float
    ipft: float
    slippage: float

    reason: str

    risk_per_share: float
    planned_risk: float
    position_value: float

    mae: float
    mfe: float
    mae_r: float
    mfe_r: float

    @property
    def pnl(self) -> float:
        """Backward-compatible net P&L property."""

        return self.net_pnl


@dataclass(frozen=True)
class PortfolioRejectedSignal:
    """Signal rejected by portfolio-level controls."""

    symbol: str
    timestamp: pd.Timestamp
    reason: str


@dataclass(frozen=True)
class PortfolioBacktestResult:
    """Complete shared-account backtest result."""

    trades: list[PortfolioTrade]
    rejected_signals: list[PortfolioRejectedSignal]
    starting_capital: float
    ending_capital: float


@dataclass
class _OpenPosition:
    """Internal state for an open long position."""

    symbol: str
    signal_time: pd.Timestamp
    entry_time: pd.Timestamp

    entry: float
    stop: float
    target: float
    quantity: int

    risk_per_share: float
    planned_risk: float
    position_value: float

    mae: float = 0.0
    mfe: float = 0.0


def _timestamp(value: object) -> pd.Timestamp:
    """Normalize a timestamp to Asia/Kolkata."""

    result = pd.Timestamp(value)

    if result.tzinfo is None:
        return result.tz_localize("Asia/Kolkata")

    return result.tz_convert("Asia/Kolkata")


def _signal_score(signal: object) -> float:
    """Return a deterministic numeric score from a signal.

    Supports both the current ``score`` attribute and the older
    ``strategy_score`` attribute used by previous tests/code.
    """

    if hasattr(signal, "score"):
        return float(signal.score)

    if hasattr(signal, "strategy_score"):
        return float(signal.strategy_score)

    return 0.0


def _build_timeline(
    data_by_symbol: dict[str, pd.DataFrame],
) -> dict[pd.Timestamp, list[tuple[str, int]]]:
    """Build a chronological timestamp -> symbol/row-index mapping.

    The mapping preserves the interface used by the existing test suite.

    Example:

        {
            Timestamp(...): [("AAA", 0), ("BBB", 0)],
            Timestamp(...): [("AAA", 1), ("BBB", 1)],
        }
    """

    timeline: dict[
        pd.Timestamp,
        list[tuple[str, int]],
    ] = {}

    for symbol, frame in data_by_symbol.items():
        if frame.empty:
            continue

        if "timestamp" not in frame.columns:
            raise ValueError(
                f"{symbol}: market data requires a timestamp column."
            )

        for row_index, timestamp in enumerate(frame["timestamp"]):
            normalized = _timestamp(timestamp)

            timeline.setdefault(
                normalized,
                [],
            ).append(
                (symbol, row_index)
            )

    for timestamp in timeline:
        timeline[timestamp].sort(
            key=lambda item: item[0]
        )

    return dict(
        sorted(
            timeline.items(),
            key=lambda item: item[0],
        )
    )


def _prepare_data(
    data_by_symbol: dict[str, pd.DataFrame],
) -> dict[str, pd.DataFrame]:
    """Normalize, validate and sort input market data."""

    prepared: dict[str, pd.DataFrame] = {}

    for symbol, frame in data_by_symbol.items():
        if frame.empty:
            continue

        data = frame.copy()

        if "timestamp" not in data.columns:
            if isinstance(data.index, pd.DatetimeIndex):
                data = data.reset_index()

                if "timestamp" not in data.columns:
                    data = data.rename(
                        columns={
                            data.columns[0]: "timestamp"
                        }
                    )
            else:
                raise ValueError(
                    f"{symbol}: market data requires a timestamp column."
                )

        data["timestamp"] = data["timestamp"].map(
            _timestamp
        )

        required = {
            "timestamp",
            "open",
            "high",
            "low",
            "close",
        }

        missing = required.difference(
            data.columns
        )

        if missing:
            raise ValueError(
                f"{symbol}: missing market-data columns: "
                + ", ".join(sorted(missing))
            )

        data = (
            data.sort_values("timestamp")
            .reset_index(drop=True)
        )

        prepared[symbol] = data

    return prepared


def _is_session_timestamp(
    timestamp: pd.Timestamp,
) -> bool:
    """Return whether a timestamp is inside the NSE equity session."""

    timestamp = _timestamp(timestamp)

    start = pd.Timestamp(
        f"{timestamp.date()} {SESSION_START}",
        tz="Asia/Kolkata",
    )

    end = pd.Timestamp(
        f"{timestamp.date()} {SESSION_END}",
        tz="Asia/Kolkata",
    )

    return start <= timestamp <= end


def _same_day(
    first: pd.Timestamp,
    second: pd.Timestamp,
) -> bool:
    """Return whether two timestamps share the same calendar date."""

    return (
        _timestamp(first).date()
        == _timestamp(second).date()
    )


def _get_row(
    data_by_symbol: dict[str, pd.DataFrame],
    symbol: str,
    row_index: int,
) -> pd.Series:
    """Return one market-data row."""

    return data_by_symbol[symbol].iloc[row_index]


def _calculate_excursion(
    position: _OpenPosition,
    row: pd.Series,
) -> None:
    """Update MAE/MFE from one observed bar.

    Long position:

        MFE = highest high - entry
        MAE = lowest low - entry

    MAE is therefore normally zero or negative.
    MFE is normally zero or positive.
    """

    high = float(row["high"])
    low = float(row["low"])

    favorable_excursion = high - position.entry
    adverse_excursion = low - position.entry

    position.mfe = max(
        position.mfe,
        favorable_excursion,
    )

    position.mae = min(
        position.mae,
        adverse_excursion,
    )


def _calculate_excursion_r(
    position: _OpenPosition,
) -> tuple[float, float, float, float]:
    """Return MAE/MFE in price and R units."""

    mae = float(position.mae)
    mfe = float(position.mfe)

    risk = float(position.risk_per_share)

    if risk <= 0:
        return mae, mfe, 0.0, 0.0

    return (
        mae,
        mfe,
        mae / risk,
        mfe / risk,
    )


def _evaluate_exit(
    position: _OpenPosition,
    row: pd.Series,
) -> tuple[float, str] | None:
    """Evaluate stop and target on the current bar.

    If both are touched during the same 5-minute candle, the stop is
    selected conservatively.
    """

    low = float(row["low"])
    high = float(row["high"])

    hit_stop = low <= position.stop
    hit_target = high >= position.target

    if hit_stop and hit_target:
        return (
            position.stop,
            "STOP_TARGET_AMBIGUITY_STOP",
        )

    if hit_stop:
        return (
            position.stop,
            "STOP",
        )

    if hit_target:
        return (
            position.target,
            "TARGET",
        )

    return None


def _cost_value(
    costs: object,
    field: str,
) -> float:
    """Read a numeric field from the cost result safely."""

    value = getattr(
        costs,
        field,
        0.0,
    )

    return float(value)


def _create_trade(
    position: _OpenPosition,
    exit_time: pd.Timestamp,
    exit_price: float,
    reason: str,
    cost_settings: CostSettings,
) -> PortfolioTrade:
    """Convert an open position into a completed trade."""

    gross_pnl = (
        exit_price - position.entry
    ) * position.quantity

    costs = calculate_trade_costs(
        entry_price=position.entry,
        exit_price=exit_price,
        quantity=position.quantity,
        settings=cost_settings,
    )

    total_cost = _cost_value(
        costs,
        "total_cost",
    )

    net_pnl = gross_pnl - total_cost

    mae, mfe, mae_r, mfe_r = (
        _calculate_excursion_r(position)
    )

    return PortfolioTrade(
        symbol=position.symbol,
        signal_time=position.signal_time,
        entry_time=position.entry_time,

        entry=position.entry,
        stop=position.stop,
        target=position.target,
        quantity=position.quantity,

        exit_time=exit_time,
        exit=exit_price,

        gross_pnl=gross_pnl,
        total_cost=total_cost,
        net_pnl=net_pnl,

        brokerage=_cost_value(
            costs,
            "brokerage",
        ),
        stt=_cost_value(
            costs,
            "stt",
        ),
        exchange_transaction_charges=_cost_value(
            costs,
            "exchange_transaction_charges",
        ),
        sebi_charges=_cost_value(
            costs,
            "sebi_charges",
        ),
        stamp_duty=_cost_value(
            costs,
            "stamp_duty",
        ),
        gst=_cost_value(
            costs,
            "gst",
        ),
        ipft=_cost_value(
            costs,
            "ipft",
        ),
        slippage=_cost_value(
            costs,
            "slippage",
        ),

        reason=reason,

        risk_per_share=position.risk_per_share,
        planned_risk=position.planned_risk,
        position_value=position.position_value,

        mae=mae,
        mfe=mfe,
        mae_r=mae_r,
        mfe_r=mfe_r,
    )


def _generate_signal(
    history: pd.DataFrame,
    symbol: str,
    settings: Settings,
    signal_generator: Callable[
        [pd.DataFrame, str, Settings],
        Signal | object | None,
    ],
) -> Signal | object | None:
    """Generate a signal from information available so far."""

    if history.empty:
        return None

    return signal_generator(
        history,
        symbol,
        settings,
    )


def run_portfolio_backtest(
    data_by_symbol: dict[str, pd.DataFrame],
    settings: Settings | None = None,
    cost_settings: CostSettings | None = None,
    signal_generator: Callable[
        [pd.DataFrame, str, Settings],
        Signal | object | None,
    ] = generate_signal,
) -> PortfolioBacktestResult:
    """Run the shared-account portfolio backtest.

    Parameters
    ----------
    data_by_symbol:
        Mapping of symbol -> OHLCV DataFrame.

    settings:
        Project settings. Defaults to ``load_settings()``.

    cost_settings:
        Trading cost model.

    signal_generator:
        Injectable signal generator used by tests and controlled experiments.

    Returns
    -------
    PortfolioBacktestResult
        Completed trades, rejected signals and ending account state.
    """

    settings = settings or load_settings()
    cost_settings = cost_settings or CostSettings()

    if not data_by_symbol:
        return PortfolioBacktestResult(
            trades=[],
            rejected_signals=[],
            starting_capital=float(
                settings.capital
            ),
            ending_capital=float(
                settings.capital
            ),
        )

    data = _prepare_data(
        data_by_symbol
    )

    if not data:
        return PortfolioBacktestResult(
            trades=[],
            rejected_signals=[],
            starting_capital=float(
                settings.capital
            ),
            ending_capital=float(
                settings.capital
            ),
        )

    timeline = _build_timeline(data)

    trades: list[PortfolioTrade] = []

    rejected_signals: list[
        PortfolioRejectedSignal
    ] = []

    capital = float(
        settings.capital
    )

    realized_pnl = 0.0

    trades_today = 0

    current_day = None

    open_position: _OpenPosition | None = None

    pending_signal: Signal | object | None = None
    pending_symbol: str | None = None
    pending_signal_time: pd.Timestamp | None = None

    # Store the latest row index observed for each symbol.
    # This allows us to construct strategy history without look-ahead.
    latest_row_index: dict[str, int] = {}

    timeline_items = list(
        timeline.items()
    )

    for timeline_position, (
        timestamp,
        symbol_rows,
    ) in enumerate(timeline_items):

        timestamp = _timestamp(timestamp)

        day = timestamp.date()

        if current_day is None:
            current_day = day

        if day != current_day:
            if open_position is not None:
                # The engine must never carry a position across dates.
                raise RuntimeError(
                    "Overnight position detected. "
                    "Portfolio backtester does not permit overnight positions."
                )

            trades_today = 0
            current_day = day

        # ---------------------------------------------------------------
        # Update latest row indices.
        # ---------------------------------------------------------------

        for symbol, row_index in symbol_rows:
            latest_row_index[symbol] = row_index

        # ---------------------------------------------------------------
        # Execute pending signal on the next bar open.
        # ---------------------------------------------------------------

        if (
            pending_signal is not None
            and pending_symbol is not None
            and pending_signal_time is not None
            and open_position is None
        ):
            matching_row = next(
                (
                    row_index
                    for symbol, row_index
                    in symbol_rows
                    if symbol == pending_symbol
                ),
                None,
            )

            if matching_row is not None:
                row = _get_row(
                    data,
                    pending_symbol,
                    matching_row,
                )

                entry_price = float(
                    row["open"]
                )

                stop = float(
                    pending_signal.stop
                )

                position_size = (
                    calculate_position_size(
                        entry=entry_price,
                        stop=stop,
                        settings=settings,
                    )
                )

                if position_size.quantity <= 0:
                    rejected_signals.append(
                        PortfolioRejectedSignal(
                            symbol=pending_symbol,
                            timestamp=pending_signal_time,
                            reason="INVALID_POSITION_SIZE",
                        )
                    )

                elif trades_today >= settings.max_trades_per_day:
                    rejected_signals.append(
                        PortfolioRejectedSignal(
                            symbol=pending_symbol,
                            timestamp=pending_signal_time,
                            reason="MAX_TRADES_PER_DAY",
                        )
                    )

                else:
                    max_daily_loss = (
                        settings.capital
                        * settings.max_daily_loss_pct
                        / 100.0
                    )

                    projected_pnl = (
                        realized_pnl
                        - float(
                            position_size.planned_risk
                        )
                    )

                    if projected_pnl < -max_daily_loss:
                        rejected_signals.append(
                            PortfolioRejectedSignal(
                                symbol=pending_symbol,
                                timestamp=pending_signal_time,
                                reason="DAILY_LOSS_LIMIT",
                            )
                        )

                    else:
                        risk_per_share = (
                            entry_price - stop
                        )

                        if risk_per_share <= 0:
                            rejected_signals.append(
                                PortfolioRejectedSignal(
                                    symbol=pending_symbol,
                                    timestamp=pending_signal_time,
                                    reason="INVALID_RISK_DISTANCE",
                                )
                            )

                        else:
                            target = (
                                entry_price
                                + (
                                    settings.risk_reward_min
                                    * risk_per_share
                                )
                            )

                            planned_risk = (
                                risk_per_share
                                * position_size.quantity
                            )

                            position_value = (
                                entry_price
                                * position_size.quantity
                            )

                            open_position = _OpenPosition(
                                symbol=pending_symbol,
                                signal_time=pending_signal_time,
                                entry_time=timestamp,

                                entry=entry_price,
                                stop=stop,
                                target=target,
                                quantity=position_size.quantity,

                                risk_per_share=risk_per_share,
                                planned_risk=planned_risk,
                                position_value=position_value,

                                mae=0.0,
                                mfe=0.0,
                            )

                            trades_today += 1

                pending_signal = None
                pending_symbol = None
                pending_signal_time = None

        # ---------------------------------------------------------------
        # Manage the currently open position.
        # ---------------------------------------------------------------

        if open_position is not None:
            matching_row = next(
                (
                    row_index
                    for symbol, row_index
                    in symbol_rows
                    if symbol == open_position.symbol
                ),
                None,
            )

            if matching_row is not None:
                row = _get_row(
                    data,
                    open_position.symbol,
                    matching_row,
                )

                _calculate_excursion(
                    open_position,
                    row,
                )

                exit_result = _evaluate_exit(
                    open_position,
                    row,
                )

                if exit_result is not None:
                    exit_price, reason = (
                        exit_result
                    )

                    trade = _create_trade(
                        position=open_position,
                        exit_time=timestamp,
                        exit_price=float(
                            exit_price
                        ),
                        reason=reason,
                        cost_settings=cost_settings,
                    )

                    trades.append(trade)

                    realized_pnl += (
                        trade.net_pnl
                    )

                    capital += trade.net_pnl

                    open_position = None

                    continue

                # The development dataset currently ends around 15:10.
                # We close on the last available bar for the position's day,
                # not at a synthetic 15:30 candle.
                is_last_bar_for_symbol = (
                    matching_row
                    == len(
                        data[
                            open_position.symbol
                        ]
                    ) - 1
                )

                next_timestamp_for_symbol = None

                if not is_last_bar_for_symbol:
                    next_timestamp_for_symbol = (
                        data[
                            open_position.symbol
                        ]
                        .iloc[
                            matching_row + 1
                        ]["timestamp"]
                    )

                    next_timestamp_for_symbol = (
                        _timestamp(
                            next_timestamp_for_symbol
                        )
                    )

                end_of_session = (
                    is_last_bar_for_symbol
                    or (
                        next_timestamp_for_symbol
                        is not None
                        and (
                            next_timestamp_for_symbol.date()
                            != timestamp.date()
                        )
                    )
                )

                if end_of_session:
                    exit_price = float(
                        row["close"]
                    )

                    trade = _create_trade(
                        position=open_position,
                        exit_time=timestamp,
                        exit_price=exit_price,
                        reason="SESSION_CLOSE",
                        cost_settings=cost_settings,
                    )

                    trades.append(trade)

                    realized_pnl += (
                        trade.net_pnl
                    )

                    capital += trade.net_pnl

                    open_position = None

                    continue

        # ---------------------------------------------------------------
        # Never generate a new signal while a position is open.
        # ---------------------------------------------------------------

        if open_position is not None:
            continue

        # ---------------------------------------------------------------
        # No signals outside the market session.
        # ---------------------------------------------------------------

        if not _is_session_timestamp(
            timestamp
        ):
            continue

        # ---------------------------------------------------------------
        # Generate candidate signals.
        #
        # Each symbol's history ends at the current row. This is the key
        # look-ahead protection.
        # ---------------------------------------------------------------

        candidates: list[
            tuple[str, Signal | object]
        ] = []

        for symbol, latest_index in latest_row_index.items():
            frame = data[symbol]

            history = frame.iloc[
                : latest_index + 1
            ].copy()

            signal = _generate_signal(
                history,
                symbol,
                settings,
                signal_generator,
            )

            if signal is None:
                continue

            candidates.append(
                (
                    symbol,
                    signal,
                )
            )

        if not candidates:
            continue

        # ---------------------------------------------------------------
        # Deterministic candidate ranking.
        #
        # Highest strategy score wins. Alphabetical symbol is the
        # deterministic tie-breaker.
        # ---------------------------------------------------------------

        candidates.sort(
            key=lambda item: (
                -_signal_score(item[1]),
                item[0],
            )
        )

        selected_symbol, selected_signal = (
            candidates[0]
        )

        pending_signal = selected_signal
        pending_symbol = selected_symbol
        pending_signal_time = timestamp

    # -------------------------------------------------------------------
    # Final safety close.
    # -------------------------------------------------------------------

    if open_position is not None:
        frame = data[
            open_position.symbol
        ]

        last_row = frame.iloc[-1]

        exit_time = _timestamp(
            last_row["timestamp"]
        )

        exit_price = float(
            last_row["close"]
        )

        trade = _create_trade(
            position=open_position,
            exit_time=exit_time,
            exit_price=exit_price,
            reason="FINAL_SAFETY_CLOSE",
            cost_settings=cost_settings,
        )

        trades.append(trade)

        realized_pnl += trade.net_pnl
        capital += trade.net_pnl

        open_position = None

    return PortfolioBacktestResult(
        trades=trades,
        rejected_signals=rejected_signals,
        starting_capital=float(
            settings.capital
        ),
        ending_capital=float(
            capital
        ),
    )


def load_processed_data(
    data_root: Path = DEFAULT_DATA_ROOT,
) -> dict[str, pd.DataFrame]:
    """Load all processed Parquet files."""

    root = Path(data_root)

    if not root.exists():
        raise FileNotFoundError(
            f"Processed data directory does not exist: {root}"
        )

    files = sorted(
        root.glob("*/*/*.parquet")
    )

    if not files:
        raise FileNotFoundError(
            f"No processed Parquet files found under {root}"
        )

    market_data: dict[
        str,
        pd.DataFrame,
    ] = {}

    for path in files:
        symbol = path.parent.parent.name

        frame = pd.read_parquet(path)

        if "symbol" in frame.columns:
            symbols = (
                frame["symbol"]
                .dropna()
                .unique()
            )

            if len(symbols) == 1:
                symbol = str(
                    symbols[0]
                )

        market_data[symbol] = frame

    return market_data


def trades_to_dataframe(
    result: PortfolioBacktestResult,
) -> pd.DataFrame:
    """Convert completed trades to a DataFrame."""

    if not result.trades:
        return pd.DataFrame(
            columns=[
                field.name
                for field
                in PortfolioTrade.__dataclass_fields__.values()
            ]
        )

    return pd.DataFrame(
        [
            asdict(trade)
            for trade in result.trades
        ]
    )


def rejected_to_dataframe(
    result: PortfolioBacktestResult,
) -> pd.DataFrame:
    """Convert rejected signals to a DataFrame."""

    if not result.rejected_signals:
        return pd.DataFrame(
            columns=[
                "symbol",
                "timestamp",
                "reason",
            ]
        )

    return pd.DataFrame(
        [
            asdict(signal)
            for signal
            in result.rejected_signals
        ]
    )


def summary_to_dataframe(
    result: PortfolioBacktestResult,
) -> pd.DataFrame:
    """Create a compact portfolio summary."""

    trades = result.trades

    total_trades = len(trades)

    wins = sum(
        1
        for trade in trades
        if trade.net_pnl > 0
    )

    losses = sum(
        1
        for trade in trades
        if trade.net_pnl <= 0
    )

    gross_pnl = sum(
        trade.gross_pnl
        for trade in trades
    )

    total_cost = sum(
        trade.total_cost
        for trade in trades
    )

    net_pnl = sum(
        trade.net_pnl
        for trade in trades
    )

    win_rate = (
        wins
        / total_trades
        * 100.0
        if total_trades
        else 0.0
    )

    return_pct = (
        net_pnl
        / result.starting_capital
        * 100.0
        if result.starting_capital
        else 0.0
    )

    return pd.DataFrame(
        [
            {
                "experiment": EXPERIMENT_NAME,
                "strategy": STRATEGY_NAME,
                "starting_capital": (
                    result.starting_capital
                ),
                "ending_capital": (
                    result.ending_capital
                ),
                "total_trades": total_trades,
                "wins": wins,
                "losses": losses,
                "win_rate_pct": win_rate,
                "gross_pnl": gross_pnl,
                "total_cost": total_cost,
                "net_pnl": net_pnl,
                "return_pct": return_pct,
                "rejected_signals": len(
                    result.rejected_signals
                ),
            }
        ]
    )


def save_reports(
    result: PortfolioBacktestResult,
    report_root: Path = DEFAULT_REPORT_ROOT,
) -> None:
    """Persist portfolio reports."""

    root = Path(report_root)

    root.mkdir(
        parents=True,
        exist_ok=True,
    )

    trades_to_dataframe(
        result
    ).to_csv(
        root / "portfolio_trades.csv",
        index=False,
    )

    rejected_to_dataframe(
        result
    ).to_csv(
        root / "portfolio_rejections.csv",
        index=False,
    )

    summary_to_dataframe(
        result
    ).to_csv(
        root / "portfolio_summary.csv",
        index=False,
    )


def main() -> None:
    """Run the shared-account portfolio backtest."""

    settings = load_settings()

    market_data = load_processed_data()

    result = run_portfolio_backtest(
        data_by_symbol=market_data,
        settings=settings,
        cost_settings=CostSettings(),
    )

    save_reports(result)

    summary = summary_to_dataframe(
        result
    ).iloc[0]

    print()
    print("=" * 72)
    print(EXPERIMENT_NAME)
    print("=" * 72)

    print(
        f"Strategy          : {STRATEGY_NAME}"
    )

    print(
        "Mode              : "
        "Shared-account historical backtest"
    )

    print(
        f"Capital           : "
        f"₹{float(summary['starting_capital']):,.2f}"
    )

    print(
        f"Stocks            : "
        f"{len(market_data)}"
    )

    print("Interval          : 5m")

    print(
        f"Total trades      : "
        f"{int(summary['total_trades'])}"
    )

    print(
        f"Rejected signals  : "
        f"{int(summary['rejected_signals'])}"
    )

    print(
        f"Wins              : "
        f"{int(summary['wins'])}"
    )

    print(
        f"Losses            : "
        f"{int(summary['losses'])}"
    )

    print(
        f"Win rate          : "
        f"{float(summary['win_rate_pct']):.2f}%"
    )

    print(
        f"Gross P&L         : "
        f"₹{float(summary['gross_pnl']):,.2f}"
    )

    print(
        f"Trading costs     : "
        f"₹{float(summary['total_cost']):,.2f}"
    )

    print(
        f"Net P&L           : "
        f"₹{float(summary['net_pnl']):,.2f}"
    )

    print(
        f"Return            : "
        f"{float(summary['return_pct']):.2f}%"
    )

    print()
    print(
        "MAE/MFE fields    : "
        "persisted to portfolio_trades.csv"
    )

    print()
    print(
        "Trades report     : "
        "data\\reports\\portfolio_trades.csv"
    )

    print(
        "Rejections report : "
        "data\\reports\\portfolio_rejections.csv"
    )

    print(
        "Summary report    : "
        "data\\reports\\portfolio_summary.csv"
    )


if __name__ == "__main__":
    main()